# Definisikan Service
services:
    app_laravel: # Nama Service (key)
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_laravel # Temen-temen bisa mengubah nama container sesuai kebutuhan, namun disarankan nama container sama dengan nama service
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
                reservations:
                    cpus: "0.2"
                    memory: 500M

    nginx: # Nama Service
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app_laravel
        networks:
            - laravel_network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    cpus: "0.2"
                    memory: 256M

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dev
        volumes:
            - dbms_mysql:/var/lib/mysql
        networks:
            - laravel_network
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 2G
                reservations:
                    cpus: "0.5"
                    memory: 1G

    pma:
        image: phpmyadmin:latest
        container_name: pma
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: dev
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - laravel_network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    cpus: "0.2"
                    memory: 256M

volumes:
    dbms_mysql:
        external: true

networks:
    laravel_network:
        driver: bridge
